### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/DATATune#11]
Hi, thank you for providing the code.

I have some questions.

Why didn't you remove sample2, which has 3789 tps and 1076 latency in the ycsb_AA?

I believe this is an outlier and could be causing poor model performance.

Could you please explain the reasoning behind keeping this sample in the dataset?

**Comment by Kwon-sein** [comment]
Hi, 🔆 

I guess I checked the question too late.

The code has been updated a lot.

If you have any additional questions, please leave an issue again.
