### ISSUE TITLE
Question about latent space optimization 

### ISSUE THREAD

**Issue by SkiddieAhn** [addb-swstarlab/DATATune#12]
I am curious whether the optimized latent feature generated during the testing process is  located within the latent space used during training. If this feature is mapped to an unseen latent space, it seems likely that decoding might not work properly. Have there been any instances where this has happened?

**Comment by Kwon-sein** [comment]
Hello. 🍀  
Thank you for your interest in my code.

If my understanding is correct, is it correct to ask whether the latent space has been properly decoded to its original dimension?

We conducted an experiment on this and wrote about it in a paper.

In the paper, the data input to the encoder during testing was plotted in 2D, and the data reconstructed through the decoder was plotted in 2D space to check whether the plot was actually similar.

If the day comes when I can present this paper,,,,  I will attach it. 🙏 

Thank you for the interesting question.
