### ISSUE TITLE
About database

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/DATATune#18]
TADA_A.ipynb uses ycss_AA, while TADA_B.ipynb uses ycss_BB.
However, I’m not sure about the difference between ycss_AA and ycss_BB.
Could you please explain the difference?

Thank you!

**Comment by Kwon-sein** [comment]
Hi
Thank you for the good question.

Different files were designated depending on MySQL workload.
A description of each workload is provided in the readme.
