### ISSUE TITLE
two questions about db tuning 

### ISSUE THREAD

**Issue by SkiddieAhn** [addb-swstarlab/DATATune#2]
First of all, thank you for your good research.
I have two questions, so I am leaving an issue.

1. Do you have any results from experiments with more diverse workloads (e.g., 5% reading, 95% writing)?
2. Do you have any experimental results on the effects of latent space variations in autoencoders?

**Comment by Kwon-sein** [comment]
Hi!
Thank you for your interest in my code.

1. 
The question about workload is workload for MySQL? Or is it a workload for RocksDB?
- For MySQL, YCSB_BB is 95% ReadRecord and 5% UpdateRecord.
- Rocksdb does not have data on read 5% and write 95%.
The 15 workloads used in the experiment are standard workloads commonly used in Rocksdb research.

2.
 We conducted experiments on various dimensions of latent space. The results of this are not in the code, but we fixed it with a latent space that shows high accuracy in predicting metrics through the latent space used in BO. We confirmed that the label (throughput, latency / Time, Rate, Waf, Sa) cannot be predicted well when reduced further than the corresponding dimension.

We will be able to upload the results later.

Thank you for the good question.
