### ISSUE TITLE
Optimization of Data Augmentation and Latin Hypercube Sampling (LHS) for Improved Performance

### ISSUE THREAD

**Issue by MedDE-DVAT** [addb-swstarlab/DATATune#21]
In our current workflow, we generate 4000 samples using Latin Hypercube Sampling (LHS) for data augmentation. We are curious about the impact of sample size on model performance:

1) Have you observed any significant performance differences when increasing or decreasing the number of generated samples?

2) Is there an optimal sample size that has consistently produced the best results in your experience?

We are interested in learning from your insights or experiments regarding the relationship between sample size and performance in similar scenarios. Thank you!

**Comment by Kwon-sein** [comment]
Hello,

Thank you for showing interest in my code.

Regarding your question about performance comparisons based on the number of samples, we have conducted experiments on this topic, which are detailed in the experimental section of our paper. (A link will be provided once the paper is accepted. 😅 )

We conducted two types of experiments based on the sample size:

1.  Comparison of AutoEncoder's reconstruction loss.

2.  Performance improvement rate of DataTune.

These experiments were conducted on four MySQL workloads as described in the README.

The results showed that when the dataset size reached 5000 samples (1000 original samples + 4000 augmented samples), the AutoEncoder's reconstruction loss decreased the most. However, when the sample size exceeded this threshold, the loss started to increase again.

Consequently, the performance of DataTune also peaked at 5000 samples.

The reason for the increased reconstruction loss when the sample size exceeds 5500 is the finite amount of information present in the dataset and the limited learning capacity of the AutoEncoder. This indicates that, despite data augmentation, there is a ceiling to the meaningful information the model can capture, and exceeding this limit may lead to a degradation in the AutoEncoder's performance.
