### ISSUE TITLE
about model architecture

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/DATATune#22]
You use the ReLU activation function in the Autoencoder.

I am curious about the effect of the activation function on the model's performance.

Could you please explain this?

Thank you.

**Comment by Kwon-sein** [comment]
Thank you for taking an interest in my code.

The reason for using ReLU in the Autoencoder is the same as why it is widely used in other deep learning models.

Our data exhibits nonlinear relationships, and we found that ReLU allows the model to better capture these features. Additionally, we experimented with various activation functions and observed that ReLU provided the best performance.

If you have any further questions, feel free to leave an issue.

Thank you!
