### ISSUE TITLE
Future work

### ISSUE THREAD

**Issue by hello-maker** [addb-swstarlab/DATATune#24]
It seems like a well-done study, but given the completeness of the research, there are a few more things to consider. 
Do you have any plans for future research to expand on this study?

**Comment by Kwon-sein** [comment]
Hello,

Thank you for your interest in my research.

As for my future work, I plan to address the current limitation of the model, which is not yet suitable for real-world online tuning applications. My goal is to develop an approach that enables online tuning for practical use in future studies.
