### ISSUE TITLE
Questions about your code

### ISSUE THREAD

**Issue by eunji00-kim** [addb-swstarlab/DATATune#26]
Hello.
First, thank you for sharing your code.

I have some questions about your DATATune.

1. What is the main difference of your DATATune comparing with previous models?
2. What kinds of evaluation metrices are used to demonstrate that the proposed model is better than other models?

Thanks.

**Comment by Kwon-sein** [comment]
Thank you for your interest in my code.

DATATune is a novel method that diverges from the traditional approaches in database parameter tuning research. In previous studies, optimization was typically performed only on the top parameters that significantly influence database performance to address the challenges of high-dimensional optimization. However, the selection of the top-k parameters varies depending on the algorithm used to extract them and the specific workload.
To overcome this limitation, DATATune reduces the information from all parameters into a latent space for optimization, enabling the use of the full parameter set in the optimization process. This approach sets DATATune apart from traditional methods.

As a performance metric, we compared the improvement in performance over the default configurations for two DBMSs, MySQL and RocksDB, against baseline models.

Thank you.
