### ISSUE TITLE
Justification for Using TabNet in Latent Space Metric Prediction

### ISSUE THREAD

**Issue by hello-maker** [addb-swstarlab/DATATune#8]
I am curious about the rationale behind using TabNet for predicting metrics in latent space. Defining latent space as tabular data seems somewhat ambiguous to me.

Additionally, I am interested in understanding the performance differences when using alternative methods such as Random Forest-based ML approaches or basic Fully Connected (FC) layers.

Could you provide some insights regarding the performance of these different methods in this context?

Thank you!

**Comment by Kwon-sein** [comment]
Hi 😄 
Thank you for your interest in my code.

1. I recognized latent space as tabular data in the form of a table that compresses various information. 

2. An experiment was conducted using a prediction model other than tabnet, with latent space as input and metric as output, and this will be updated in a file called sac_experiment later.

Looking at the experimental results, it was confirmed that tabnet actually had the highest performance accuracy and was good at predicting multiple labels. 

Based on these results, it seems that latent space can be considered a tabular data format.

If you have any additional questions, please leave an issue.
