### ISSUE TITLE
Questions on Early Stopping Criteria and Hyperparameter Selection

### ISSUE THREAD

**Issue by jeongeunKim-art** [addb-swstarlab/DATATune#9]
I was very impressed by your research, and I have a few questions I'd like to ask
Is there a standard for early stopping like patience=200 for tada_bb and patience=100 for tata?
I was wondering if it was given randomly or if you found the best hyperparameter combination separately.. 

Thank you

**Comment by Kwon-sein** [comment]
Hello. Thank you for your interest in my code.
The values ​​for patience were placed differently depending on the data. 

However, the hyperparameters were not randomly assigned, but rather the hyperparameter with the best value was designated after conducting experiments with various values.

If you have any additional questions, please leave an issue.
